dist: trusty
language: python
python: 3.6
cache: 
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python3.6.3/lib/python3.6/site-packages
matrix:
  include:
    - env: SCRIPT=TEST
    - env: SCRIPT=LINT
    - env: SCRIPT=DOCSTYLE
before_install:
  - pip3 install pylint pydocstyle pytest-cov coveralls
script:
  - if [ "$SCRIPT" = "TEST" ]; then py.test --cov . && coveralls; fi
  - if [ "$SCRIPT" = "LINT" ]; then pylint *.py tests/*.py; fi
  - if [ "$SCRIPT" = "DOCSTYLE" ]; then pydocstyle *.py; fi
