dist: trusty
language: python
python: 3.6
matrix:
  include:
    - env: SCRIPT=TEST
    - env: SCRIPT=LINT
    - env: SCRIPT=DOCSTYLE
before_install:
  - pip3 install pylint pydocstyle pytest-cov coveralls
script:
  - if [ "$SCRIPT" = "TEST" ]; then py.test && coveralls; fi
  - if [ "$SCRIPT" = "LINT" ]; then pylint *.py tests/*.py; fi
  - if [ "$SCRIPT" = "DOCSTYLE" ]; then pydocstyle *.py; fi
